version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecurepassword
      MYSQL_DATABASE: sailsdb
      MYSQL_USER: sailsuser
      MYSQL_PASSWORD: sailspassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - sailsnetwork

  sailsjs:
    image: node:18
    container_name: sailsjs_container
    restart: always
    working_dir: /usr/src/app
    volumes:
      - ./sails-app:/usr/src/app
      - ./controllers:/tmp/controllers  
      - ./routes.js:/tmp/routes.js
      - ./entrypoint.sh:/usr/src/app/entrypoint.sh
    ports:
      - "1337:1337"
    command: sh /usr/src/app/entrypoint.sh
    depends_on:
      - mariadb
    networks:
      - sailsnetwork

volumes:
  mysql-data:
    driver: local

networks:
  sailsnetwork:
    driver: bridge
