version: '3.8'

services:
  mariadb:
    image: mariadb:latest
    container_name: mariadb_container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysecurepassword
      MYSQL_DATABASE: sailsdb
      MYSQL_USER: sailsuser
      MYSQL_PASSWORD: sailspassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - sailsnetwork

  sailsjs:
    build:
      context: ./sails-app
      dockerfile: Dockerfile
    container_name: sailsjs_container
    restart: always
    ports:
      - "1337:1337"
    depends_on:
      - mariadb
    networks:
      - sailsnetwork
    environment:
      - CORS_ALL_ROUTES=true
      - CORS_ALLOW_ORIGINS=http://localhost:3000,http://example.com
      - CSRF_ENABLED=true
      - SESSION_SECRET=mySuperSecretSessionKey
      - SESSION_HTTPS=false
      - DATABASE_URL=mysql://sailsuser:sailspassword@mariadb:3306/sailsdb
  db-backup:
    build:
      context: ./backup
      dockerfile: Dockerfile
    container_name: db_backup_container
    depends_on:
      - mariadb
    volumes:
      - db-backups:/backups
    networks:
      - sailsnetwork

volumes:
  mysql-data:
  db-backups:

networks:
  sailsnetwork:
    driver: bridge
